version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NODE_ENV=production
      - SERVER_API=http://server:8000
    command: npm run dev
