version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: devonaut-server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app  # Bind mount local server directory to container
      - /app/__pycache__/  # Prevent caching issues
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/users?authSource=admin
      - SECRET_KEY=SDflkjsdS:DLKFJ
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Enable auto-reload

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: devonaut-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app  
      - /app/node_modules  
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - SERVER_API=http://server:8000
    command: npm run dev  
