name: Deploy
on:
  push:
    branches: [feature/create-questions]
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.USER_NAME }}@${{ secrets.SSH_HOST }} '
            sudo docker-compose -f docker-compose.prod.yml up -d --build
          '
