name: Deploy
on:
  push:
    branches: [feature/create-questions]
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug SSH connection
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          echo "Attempting to connect to ${USER_NAME}@${HOSTNAME}..."
          ssh -i private_key ${USER_NAME}@${HOSTNAME} 'echo "Connection successful"'
          
      - name: Deploy with Docker Compose
        if: success()
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          ssh -v -i private_key ${USER_NAME}@${HOSTNAME} '
            sudo docker-compose -f docker-compose.prod.yml up -d --build
          '
