name: Deploy to EC2
on:
  # Trigger on direct commits to production branch
  push:
    branches: [production]
  # Also trigger when PRs to production are merged
  pull_request:
    types: [closed]
    branches: [production]
jobs:
  deploy:
    # Run on direct push to production OR when a PR is merged (not just closed)
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ~/Devonaut && \
          git fetch origin production && \
          git reset --hard origin/production && \
          sudo docker-compose -f docker-compose.prod.yml down && \
          sudo docker system prune -f && \
          sudo rm -rf /var/lib/docker/overlay2/* && \
          sudo docker-compose -f docker-compose.prod.yml up -d --build"
